import './globals.css';
import { Inter } from 'next/font/google';

import { API_MOCKING } from '@/config/constants';
import { MSWWrapper } from '@/lib/msw';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MSWWrapper>{children}</MSWWrapper>
      </body>
    </html>
  );
}
